import {
  CaretDown,
  CaretUp,
  CaretLeft,
  MagnifyingGlass,
  MusicNotes,
  Pause,
  Play,
  Playlist,
  Radio,
  Repeat,
  RepeatOnce,
  Shuffle,
  SkipBack,
  SkipForward,
  SpeakerHigh,
  SpeakerSlash,
  SpinnerGap,
  Trash,
  Waveform,
  X,
  Article,
  Heart,
  Folder,
  PencilSimple,
  Plus,
} from '@phosphor-icons/react';

export const musicIcons = {
  caretDown: CaretDown,
  caretUp: CaretUp,
  caretLeft: CaretLeft,
  close: X,
  heart: Heart,
  loading: SpinnerGap,
  lyrics: Article,
  music: MusicNotes,
  next: SkipForward,
  pause: Pause,
  play: Play,
  playlist: Playlist,
  previous: SkipBack,
  radio: Radio,
  repeat: Repeat,
  repeatOne: RepeatOnce,
  search: MagnifyingGlass,
  shuffle: Shuffle,
  trash: Trash,
  volume: SpeakerHigh,
  volumeMuted: SpeakerSlash,
  waveform: Waveform,
  folder: Folder,
  edit: PencilSimple,
  plus: Plus,
} as const;
